#!/bin/bash

set -e

export SERVICE_NAME=go-gin-boilerplate
export PORT="4006"
export DATABASE_URL=$DATABASE_URL_LOCAL_DAO

go test ./...
go build -tags=jsoniter -o build/application
./build/application
